version: '3.8'

services:
  web:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ../projeto_mc426:/projeto_mc426
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /projeto_mc426
volumes:
  static_volume:
