# Generated by Django 4.2 on 2023-12-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='aaa',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
