# Generated by Django 4.2 on 2023-11-23 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_de_ocorrencia',
            fields=[
                ('tdo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tdo_nome', models.CharField(max_length=255)),
                ('tdo_peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='registro_de_ocorrencia',
            fields=[
                ('rdo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rdo_cep', models.CharField(max_length=50, verbose_name='CEP')),
                ('rdo_rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('rdo_bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('rdo_cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('rdo_estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('rdo_numero', models.IntegerField(verbose_name='Número')),
                ('rdo_lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitude')),
                ('rdo_lng', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitute')),
                ('rdo_dtocorrencia', models.DateField(verbose_name='Data da Ocorrência')),
                ('rdo_hrocorrencia', models.TimeField(verbose_name='Hora da Ocorrência')),
                ('rdo_tdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipo_de_ocorrencia')),
            ],
        ),
    ]
