# Generated by Django 4.2 on 2023-12-13 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_registro_de_ocorrencia_tipo_de_ocorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_de_ocorrencia',
            name='rdo_tdo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipo_de_ocorrencia', verbose_name='Tipo de Ocorrência'),
        ),
    ]
