# Generated by Django 4.2 on 2023-12-11 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0002_rename_profile_customprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='location_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='latitude')),
                ('user_lng', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='longitude')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomProfile',
        ),
    ]
