# Generated by Django 4.2 on 2023-12-15 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_locationprofile_user_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationprofile',
            name='user_lng',
            field=models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)], verbose_name='longitude'),
        ),
    ]
